### ISSUE TITLE
Debug: Cannot estimate gas

### ISSUE THREAD

**Issue by alexbobes** [cusdt-LINK/kcc-flashswap-arb#3]
debug: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":3,"_isProviderError":true,"data":"xxxxxxx"}, method="call", transaction={"from":"xxx","to":"xxx","data":"xxxxx","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.3)

What should be the solution for fixing this, do you think slippage tolerance can be modified in order to fix it?

Thank you.

**Comment by gweidart** [comment]
@mrbxx Fixed in my latest commit. Certain tokens are not compatible. The bot has trouble with tokens with less than 18 decimals. Keep this in mind if you are editing tokens.ts. You will need to update with the fixed commit and delete the KCC-PAIRS.json before restarting the bot.

**Comment by alexbobes** [comment]
@cusdt-LINK  thank you; still getting the error on one of the tokens; what is the best way to identify < 18 decimals tokens?

**Comment by gweidart** [comment]
> @cusdt-LINK thank you; still getting the error on one of the tokens; what is the best way to identify < 18 decimals tokens?

Are you asking what’s the best way to find out if a token has less than 18 decimals? 

If so, you can check the respective explorer. It almost always list how many decimals a specific token has.

**Comment by alexbobes** [comment]
Yes, I was thinking of automating the decimals verification for configured tokens.
Thank you.

**Comment by gweidart** [comment]
Resolved. Closed.
